export const STATUS = {
  APPLICABLE: true,
  NON_APPLICABLE: false,
};

export const CHRISMAS_D_DAY = {
  EVENT_DEADLINE: 25,
  DEFAULT_DISCOUNT: 1000,
  BONUS_DISCOUNT: 100,
};

export const GIVEAWAY_EVENT = {
  APPLICABLE_AMOUNT: 120000,
};

export const EVENT = {
  APPLICABLE_AMOUNT: 10000,
  DISCOUNT: 2023,
};

export const WEEKDAY_EVENT = {
  NON_APPLICABLE_DATES: [1, 2, 8, 9, 15, 16, 22, 23, 29, 30],
};
